package com.sample;

import com.sample.Objects.Pozycja;
import com.sample.Objects.Ego;
import com.sample.Objects.Agresja;
import com.sample.Objects.Zel;
import com.sample.Objects.Nurkowanie;
import com.sample.Objects.Wypady;
import com.sample.Objects.Szczescie;
import com.sample.Objects.Wzrost; 
import com.sample.Objects.Wiek;
import com.sample.Objects.Banany;
import com.sample.Objects.Taktyka;
import com.sample.Objects.Imprezy;
import com.sample.Objects.Lider;
import com.sample.Objects.Podejscie;
import com.sample.Objects.Ogrodnik;
import com.sample.Objects.Broda;
import com.sample.Objects.Zaimponowanie;
import com.sample.Objects.Samolubnosc;
import com.sample.Objects.Chipsy;
import com.sample.Objects.Gryzienie;

//Baza wiedzy

//GK

rule "Neuer"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == true)
	then
        MainWindow.instance().showAnswerPanel("Jesteś Manuelem Neuerem!",
                                              "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Neuer.jpg");
end

rule "Kuszczak"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == false)
		exists Szczescie(value == 0)
	then
		System.out.println("Jesteś Tomaszem Kuszczakiem!");
        MainWindow.instance().showAnswerPanel("Jesteś Tomaszem Kuszczakiem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Kuszczak.jpg");
end

rule "Szczesny"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == false)
		exists Szczescie(value == 2)
	then
		System.out.println("Jesteś Wojciechem Szczęsnym!");
        MainWindow.instance().showAnswerPanel("Jesteś Wojciechem Szczęsnym!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Szczesny.jpg");
end

rule "Courtois"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == false)
		exists Szczescie(value == 1)
		exists Wiek(value == 0)
	then
		System.out.println("Jesteś Thibaut Courtois!");
        MainWindow.instance().showAnswerPanel("Jesteś Thibaut Courtois!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Courtois.jpg");
end

rule "Lloris"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == false)
		exists Szczescie(value == 1)
		exists Wiek(value == 1)
	then
		System.out.println("Jesteś Hugo Llorisem!");
        MainWindow.instance().showAnswerPanel("Jesteś Hugo Llorisem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Lloris.jpg");
end

rule "Casillas"
	when
		exists Pozycja(value == 0)
		exists Wypady(value == false)
		exists Szczescie(value == 1)
		exists Wiek(value == 2)
	then
		System.out.println("Jesteś Ikerem Casillasem!");
        MainWindow.instance().showAnswerPanel("Jesteś Ikerem Casillasem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Casillas.jpg");
end

//DEF 

rule "Mascherano"
	when
		exists Pozycja(value == 1)
		exists Wzrost(value <= 1)
	then
		System.out.println("Jesteś Javierem Mascherano!");
        MainWindow.instance().showAnswerPanel("Jesteś Javierem Mascherano!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Mascherano.jpg");
end

rule "Pepe"
	when
		exists Pozycja(value == 1)
		exists Agresja(value == 2)
	then
		System.out.println("Jesteś Pepe!");
        MainWindow.instance().showAnswerPanel("Jesteś Pepe!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Pepe.jpg");
end

rule "Cionek"
	when
		exists Pozycja(value == 1)
		exists Agresja(value != 2)
		exists Taktyka(value == 0)
	then
		System.out.println("Jesteś Thiago Cionkiem!");
        MainWindow.instance().showAnswerPanel("Jesteś Thiago Cionkiem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Cionek.jpg");
end

rule "Thiago Silva"
	when
		exists Pozycja(value == 1)
		exists Agresja(value != 2)
		exists Taktyka(value == 2)
	then
		System.out.println("Jesteś Thiago Silvą!");
        MainWindow.instance().showAnswerPanel("Jesteś Thiago Silvą!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Thiago Silva.jpg");
end

rule "Sergio Ramos"
	when
		exists Pozycja(value == 1)
		exists Agresja(value != 2)
		exists Taktyka(value == 1)
		exists Lider(value == true)
	then
		System.out.println("Jesteś Sergio Ramosem!");
        MainWindow.instance().showAnswerPanel("Jesteś Sergio Ramosem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Sergio Ramos.jpg");
end

rule "Alves"
	when
		exists Pozycja(value == 1)
		exists Agresja(value != 2)
		exists Taktyka(value == 1)
		exists Lider(value == false)
		exists Banany(value == true)
	then
		System.out.println("Jesteś Danim Alvesem!");
        MainWindow.instance().showAnswerPanel("Jesteś Danim Alvesem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Alves.jpg");
end

rule "Luiz"
	when
		exists Pozycja(value == 1)
		exists Agresja(value != 2)
		exists Taktyka(value == 1)
		exists Lider(value == false)
		exists Banany(value == false)
	then
		System.out.println("Jesteś Davidem Luizem!");
        MainWindow.instance().showAnswerPanel("Jesteś Davidem Luizem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Luiz.jpg");
end

//MID

rule "Xavi"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 0)
		exists Ogrodnik(value == true)
	then
		System.out.println("Jesteś Xavim!");
        MainWindow.instance().showAnswerPanel("Jesteś Xavim!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Xavi.jpg");
end

rule "Modric"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 0)
		exists Ogrodnik(value == false)
		exists Broda(value == false)
	then
		System.out.println("Jesteś Luką Moriciem!");
        MainWindow.instance().showAnswerPanel("Jesteś Luką Moriciem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Modric.jpg");
end

rule "Xabi"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 0)
		exists Ogrodnik(value == false)
		exists Broda(value == true)
		exists Zaimponowanie(value == true)
	then
		System.out.println("Jesteś Xabim Alonso!");
        MainWindow.instance().showAnswerPanel("Jesteś Xabim Alonso!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Xabi.jpg");
end

rule "Pirlo"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 0)
		exists Ogrodnik(value == false)
		exists Broda(value == true)
		exists Zaimponowanie(value == false)
	then
		System.out.println("Jesteś Andrea Pirlo!");
        MainWindow.instance().showAnswerPanel("Jesteś Andrea Pirlo!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Pirlo.jpg");
end

rule "Fabregas"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 1)
		exists Samolubnosc(value == 0)
	then
		System.out.println("Jesteś Cescem Fabregasem!");
        MainWindow.instance().showAnswerPanel("Jesteś Cescem Fabregasem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Fabregas.jpg");
end

rule "Isco"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 1)
		exists Samolubnosc(value == 1)
	then
		System.out.println("Jesteś Isco!");
        MainWindow.instance().showAnswerPanel("Jesteś Isco!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Isco.jpg");
end

rule "Robben"
	when
		exists Pozycja(value == 2)
		exists Podejscie(value == 1)
		exists Samolubnosc(value == 2)
	then
		System.out.println("Jesteś Arienem Robbenem!");
        MainWindow.instance().showAnswerPanel("Jesteś Arienem Robbenem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Robben.jpg");
end

//ATCK

rule "Giovinco"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value == 0)
		exists Chipsy(value == false)
	then
		System.out.println("Jesteś Sebastianem Giovinco!");
        MainWindow.instance().showAnswerPanel("Jesteś Sebastianem Giovinco!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Giovinco.jpg");
end

rule "Messi"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value == 0)
		exists Chipsy(value == true)
	then
		System.out.println("Jesteś Lionelem Messim!");
        MainWindow.instance().showAnswerPanel("Jesteś Lionelem Messim!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Messi.jpg");
end

rule "Balotelli"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == true)
	then
		System.out.println("Jesteś Mario Balotellim!");
        MainWindow.instance().showAnswerPanel("Jesteś Mario Balotellim!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Balotelli.jpg");
end

rule "Benzema"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
		exists Ego(value == 0)
	then
		System.out.println("Jesteś Karimem Benzemą!");
        MainWindow.instance().showAnswerPanel("Jesteś Karimem Benzemą!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Benzema.jpg");
end
 
rule "Zlatan"
 	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 2)
 	then
 		System.out.println("Jesteś Zlatanem Ibrahimowiciem!");
        MainWindow.instance().showAnswerPanel("Jesteś Zlatanem Ibrahimowiciem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Zlatan.jpg");
end

rule "Lewandowski"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 1)
 		exists Nurkowanie(value == false)
 	then
 		System.out.println("Jesteś Robertem Lewandowskim!");
        MainWindow.instance().showAnswerPanel("Jesteś Robertem Lewandowskim!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Lewandowski.jpg");
end

rule "Neymar"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 1)
 		exists Nurkowanie(value == true)
		exists Zel(value == 1)
	then
		System.out.println("Jesteś Neymarem!");
        MainWindow.instance().showAnswerPanel("Jesteś Neymarem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Neymar.jpg");
end

rule "Ronaldo"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 1)
 		exists Nurkowanie(value == true)
		exists Zel(value == 2)
	then
		System.out.println("Jesteś Cristiano Ronaldo!");
        MainWindow.instance().showAnswerPanel("Jesteś Cristiano Ronaldo!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Ronaldo.jpg");
end

rule "Rooney"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 1)
 		exists Nurkowanie(value == true)
		exists Zel(value == 0)
		exists Gryzienie(value == false)
	then
		System.out.println("Jesteś Waynem Rooney'em!");
        MainWindow.instance().showAnswerPanel("Jesteś Waynem Rooney'em!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Rooney.jpg");
end

rule "Suarez"
	when
		exists Pozycja(value == 3)
		exists Wzrost(value > 0)
		exists Imprezy(value == false)
 		exists Ego(value == 1)
 		exists Nurkowanie(value == true)
		exists Zel(value == 0)
		exists Gryzienie(value == true)
	then
		System.out.println("Jesteś Suarezem!");
        MainWindow.instance().showAnswerPanel("Jesteś Suarezem!", "/home/jarasz/dev/java/put/si/drools/SI-system-ekspercki-/img/Suarez.jpg");
end
